[project]
name = "nkconfighandler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "psycopg[binary]>=3.2.10",
    "pydantic>=2.11.9",
    "ruff>=0.13.0",
]
